// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions, useQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteWorkflow, getActivity, getAllTags, getAllUsers, getConfigfiles, getDetail, getJob, getJobOutputs, getJobs, getLogs, getProgress, getRuleDuration, getRuleError, getRuleGraph, getRuleStatus, getSnakefile, getStatus, getSystemHealth, getSystemHealthAsync, getSystemResources, getTimelines, getUserSummary, getWorkflowIdByName, getWorkflowLogs, getWorkflows, listFiles, type Options, postPruning, streamEvents, streamWorkflowLogsSse } from '../sdk.gen';
import type { DeleteWorkflowData, DeleteWorkflowError, GetActivityData, GetActivityError, GetActivityResponse, GetAllTagsData, GetAllTagsResponse, GetAllUsersData, GetAllUsersResponse, GetConfigfilesData, GetConfigfilesError, GetConfigfilesResponse, GetDetailData, GetDetailError, GetDetailResponse, GetJobData, GetJobError, GetJobOutputsData, GetJobOutputsError, GetJobOutputsResponse, GetJobResponse, GetJobsData, GetJobsError, GetJobsResponse, GetLogsData, GetLogsError, GetLogsResponse, GetProgressData, GetProgressError, GetProgressResponse, GetRuleDurationData, GetRuleDurationError, GetRuleDurationResponse, GetRuleErrorData, GetRuleErrorError, GetRuleErrorResponse, GetRuleGraphData, GetRuleGraphError, GetRuleGraphResponse, GetRuleStatusData, GetRuleStatusError, GetRuleStatusResponse, GetSnakefileData, GetSnakefileError, GetSnakefileResponse, GetStatusData, GetStatusError, GetStatusResponse, GetSystemHealthAsyncData, GetSystemHealthAsyncResponse, GetSystemHealthData, GetSystemHealthResponse, GetSystemResourcesData, GetSystemResourcesResponse, GetTimelinesData, GetTimelinesError, GetTimelinesResponse, GetUserSummaryData, GetUserSummaryResponse, GetWorkflowIdByNameData, GetWorkflowIdByNameError, GetWorkflowIdByNameResponse, GetWorkflowLogsData, GetWorkflowLogsError, GetWorkflowLogsResponse, GetWorkflowsData, GetWorkflowsError, GetWorkflowsResponse, ListFilesData, ListFilesError, ListFilesResponse, PostPruningData, PostPruningResponse, StreamEventsData, StreamEventsError, StreamWorkflowLogsSseData, StreamWorkflowLogsSseError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getSystemResourcesQueryKey = (options?: Options<GetSystemResourcesData>) => createQueryKey('getSystemResources', options, false, ['summary']);

/**
 * Get System Resources
 */
export const getSystemResourcesOptions = (options?: Options<GetSystemResourcesData>) => queryOptions<GetSystemResourcesResponse, DefaultError, GetSystemResourcesResponse, ReturnType<typeof getSystemResourcesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemResources({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemResourcesQueryKey(options)
});

/**
 * Get System Resources
 */
export const useGetSystemResourcesQuery = (options?: Options<GetSystemResourcesData>) => useQuery(getSystemResourcesOptions(options));

export const getUserSummaryQueryKey = (options?: Options<GetUserSummaryData>) => createQueryKey('getUserSummary', options, false, ['summary']);

/**
 * Get User Summary
 */
export const getUserSummaryOptions = (options?: Options<GetUserSummaryData>) => queryOptions<GetUserSummaryResponse, DefaultError, GetUserSummaryResponse, ReturnType<typeof getUserSummaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserSummary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserSummaryQueryKey(options)
});

/**
 * Get User Summary
 */
export const useGetUserSummaryQuery = (options?: Options<GetUserSummaryData>) => useQuery(getUserSummaryOptions(options));

export const getStatusQueryKey = (options: Options<GetStatusData>) => createQueryKey('getStatus', options, false, ['summary']);

/**
 * Get Status
 */
export const getStatusOptions = (options: Options<GetStatusData>) => queryOptions<GetStatusResponse, GetStatusError, GetStatusResponse, ReturnType<typeof getStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStatusQueryKey(options)
});

/**
 * Get Status
 */
export const useGetStatusQuery = (options: Options<GetStatusData>) => useQuery(getStatusOptions(options));

export const getActivityQueryKey = (options: Options<GetActivityData>) => createQueryKey('getActivity', options, false, ['summary']);

/**
 * Get Activity
 */
export const getActivityOptions = (options: Options<GetActivityData>) => queryOptions<GetActivityResponse, GetActivityError, GetActivityResponse, ReturnType<typeof getActivityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getActivity({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getActivityQueryKey(options)
});

/**
 * Get Activity
 */
export const useGetActivityQuery = (options: Options<GetActivityData>) => useQuery(getActivityOptions(options));

export const getRuleErrorQueryKey = (options?: Options<GetRuleErrorData>) => createQueryKey('getRuleError', options, false, ['summary']);

/**
 * Get Rule Error
 */
export const getRuleErrorOptions = (options?: Options<GetRuleErrorData>) => queryOptions<GetRuleErrorResponse, GetRuleErrorError, GetRuleErrorResponse, ReturnType<typeof getRuleErrorQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleError({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleErrorQueryKey(options)
});

/**
 * Get Rule Error
 */
export const useGetRuleErrorQuery = (options?: Options<GetRuleErrorData>) => useQuery(getRuleErrorOptions(options));

export const getRuleDurationQueryKey = (options?: Options<GetRuleDurationData>) => createQueryKey('getRuleDuration', options, false, ['summary']);

/**
 * Get Rule Duration
 */
export const getRuleDurationOptions = (options?: Options<GetRuleDurationData>) => queryOptions<GetRuleDurationResponse, GetRuleDurationError, GetRuleDurationResponse, ReturnType<typeof getRuleDurationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleDuration({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleDurationQueryKey(options)
});

/**
 * Get Rule Duration
 */
export const useGetRuleDurationQuery = (options?: Options<GetRuleDurationData>) => useQuery(getRuleDurationOptions(options));

/**
 * Post Pruning
 */
export const postPruningMutation = (options?: Partial<Options<PostPruningData>>): UseMutationOptions<PostPruningResponse, DefaultError, Options<PostPruningData>> => {
    const mutationOptions: UseMutationOptions<PostPruningResponse, DefaultError, Options<PostPruningData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPruning({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSystemHealthQueryKey = (options?: Options<GetSystemHealthData>) => createQueryKey('getSystemHealth', options, false, ['summary']);

/**
 * Get System Health
 *
 * 检查系统健康状态，包括数据库和SSE服务（同步版本）
 */
export const getSystemHealthOptions = (options?: Options<GetSystemHealthData>) => queryOptions<GetSystemHealthResponse, DefaultError, GetSystemHealthResponse, ReturnType<typeof getSystemHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemHealthQueryKey(options)
});

/**
 * Get System Health
 *
 * 检查系统健康状态，包括数据库和SSE服务（同步版本）
 */
export const useGetSystemHealthQuery = (options?: Options<GetSystemHealthData>) => useQuery(getSystemHealthOptions(options));

export const getSystemHealthAsyncQueryKey = (options?: Options<GetSystemHealthAsyncData>) => createQueryKey('getSystemHealthAsync', options, false, ['summary']);

/**
 * Get System Health Async
 *
 * 检查系统健康状态，包括数据库和SSE服务（异步版本，包含完整SSE检查）
 */
export const getSystemHealthAsyncOptions = (options?: Options<GetSystemHealthAsyncData>) => queryOptions<GetSystemHealthAsyncResponse, DefaultError, GetSystemHealthAsyncResponse, ReturnType<typeof getSystemHealthAsyncQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemHealthAsync({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemHealthAsyncQueryKey(options)
});

/**
 * Get System Health Async
 *
 * 检查系统健康状态，包括数据库和SSE服务（异步版本，包含完整SSE检查）
 */
export const useGetSystemHealthAsyncQuery = (options?: Options<GetSystemHealthAsyncData>) => useQuery(getSystemHealthAsyncOptions(options));

export const getAllUsersQueryKey = (options?: Options<GetAllUsersData>) => createQueryKey('getAllUsers', options, false, ['workflow']);

/**
 * Get All Users
 */
export const getAllUsersOptions = (options?: Options<GetAllUsersData>) => queryOptions<GetAllUsersResponse, DefaultError, GetAllUsersResponse, ReturnType<typeof getAllUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllUsersQueryKey(options)
});

/**
 * Get All Users
 */
export const useGetAllUsersQuery = (options?: Options<GetAllUsersData>) => useQuery(getAllUsersOptions(options));

export const getJobsQueryKey = (options: Options<GetJobsData>) => createQueryKey('getJobs', options, false, ['workflow']);

/**
 * Get Jobs
 */
export const getJobsOptions = (options: Options<GetJobsData>) => queryOptions<GetJobsResponse, GetJobsError, GetJobsResponse, ReturnType<typeof getJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getJobsInfiniteQueryKey = (options: Options<GetJobsData>): QueryKey<Options<GetJobsData>> => createQueryKey('getJobs', options, true);

/**
 * Get Jobs
 */
export const getJobsInfiniteOptions = (options: Options<GetJobsData>) => infiniteQueryOptions<GetJobsResponse, GetJobsError, InfiniteData<GetJobsResponse>, QueryKey<Options<GetJobsData>>, number | null | Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getJobs({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsInfiniteQueryKey(options)
});

/**
 * Get Jobs
 */
export const useGetJobsQuery = (options: Options<GetJobsData>) => useQuery(getJobsOptions(options));

export const getWorkflowsQueryKey = (options?: Options<GetWorkflowsData>) => createQueryKey('getWorkflows', options, false, ['workflow']);

/**
 * Get Workflows
 */
export const getWorkflowsOptions = (options?: Options<GetWorkflowsData>) => queryOptions<GetWorkflowsResponse, GetWorkflowsError, GetWorkflowsResponse, ReturnType<typeof getWorkflowsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflows({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowsQueryKey(options)
});

export const getWorkflowsInfiniteQueryKey = (options?: Options<GetWorkflowsData>): QueryKey<Options<GetWorkflowsData>> => createQueryKey('getWorkflows', options, true);

/**
 * Get Workflows
 */
export const getWorkflowsInfiniteOptions = (options?: Options<GetWorkflowsData>) => infiniteQueryOptions<GetWorkflowsResponse, GetWorkflowsError, InfiniteData<GetWorkflowsResponse>, QueryKey<Options<GetWorkflowsData>>, number | null | Pick<QueryKey<Options<GetWorkflowsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetWorkflowsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkflows({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowsInfiniteQueryKey(options)
});

/**
 * Get Workflows
 */
export const useGetWorkflowsQuery = (options?: Options<GetWorkflowsData>) => useQuery(getWorkflowsOptions(options));

export const getRuleGraphQueryKey = (options: Options<GetRuleGraphData>) => createQueryKey('getRuleGraph', options, false, ['workflow']);

/**
 * Get Rule Graph
 */
export const getRuleGraphOptions = (options: Options<GetRuleGraphData>) => queryOptions<GetRuleGraphResponse, GetRuleGraphError, GetRuleGraphResponse, ReturnType<typeof getRuleGraphQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleGraph({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleGraphQueryKey(options)
});

/**
 * Get Rule Graph
 */
export const useGetRuleGraphQuery = (options: Options<GetRuleGraphData>) => useQuery(getRuleGraphOptions(options));

export const getDetailQueryKey = (options: Options<GetDetailData>) => createQueryKey('getDetail', options, false, ['workflow']);

/**
 * Get Detail
 */
export const getDetailOptions = (options: Options<GetDetailData>) => queryOptions<GetDetailResponse, GetDetailError, GetDetailResponse, ReturnType<typeof getDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDetailQueryKey(options)
});

/**
 * Get Detail
 */
export const useGetDetailQuery = (options: Options<GetDetailData>) => useQuery(getDetailOptions(options));

export const getRuleStatusQueryKey = (options: Options<GetRuleStatusData>) => createQueryKey('getRuleStatus', options, false, ['workflow']);

/**
 * Get Rule Status
 */
export const getRuleStatusOptions = (options: Options<GetRuleStatusData>) => queryOptions<GetRuleStatusResponse, GetRuleStatusError, GetRuleStatusResponse, ReturnType<typeof getRuleStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleStatusQueryKey(options)
});

/**
 * Get Rule Status
 */
export const useGetRuleStatusQuery = (options: Options<GetRuleStatusData>) => useQuery(getRuleStatusOptions(options));

export const getSnakefileQueryKey = (options: Options<GetSnakefileData>) => createQueryKey('getSnakefile', options, false, ['workflow']);

/**
 * Get Snakefile
 */
export const getSnakefileOptions = (options: Options<GetSnakefileData>) => queryOptions<GetSnakefileResponse, GetSnakefileError, GetSnakefileResponse, ReturnType<typeof getSnakefileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSnakefile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSnakefileQueryKey(options)
});

/**
 * Get Snakefile
 */
export const useGetSnakefileQuery = (options: Options<GetSnakefileData>) => useQuery(getSnakefileOptions(options));

export const getConfigfilesQueryKey = (options: Options<GetConfigfilesData>) => createQueryKey('getConfigfiles', options, false, ['workflow']);

/**
 * Get Configfiles
 */
export const getConfigfilesOptions = (options: Options<GetConfigfilesData>) => queryOptions<GetConfigfilesResponse, GetConfigfilesError, GetConfigfilesResponse, ReturnType<typeof getConfigfilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConfigfiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConfigfilesQueryKey(options)
});

/**
 * Get Configfiles
 */
export const useGetConfigfilesQuery = (options: Options<GetConfigfilesData>) => useQuery(getConfigfilesOptions(options));

export const getProgressQueryKey = (options: Options<GetProgressData>) => createQueryKey('getProgress', options, false, ['workflow']);

/**
 * Get Progress
 */
export const getProgressOptions = (options: Options<GetProgressData>) => queryOptions<GetProgressResponse, GetProgressError, GetProgressResponse, ReturnType<typeof getProgressQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProgress({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProgressQueryKey(options)
});

/**
 * Get Progress
 */
export const useGetProgressQuery = (options: Options<GetProgressData>) => useQuery(getProgressOptions(options));

export const getTimelinesQueryKey = (options: Options<GetTimelinesData>) => createQueryKey('getTimelines', options, false, ['workflow']);

/**
 * Get Timelines
 */
export const getTimelinesOptions = (options: Options<GetTimelinesData>) => queryOptions<GetTimelinesResponse, GetTimelinesError, GetTimelinesResponse, ReturnType<typeof getTimelinesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTimelines({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTimelinesQueryKey(options)
});

/**
 * Get Timelines
 */
export const useGetTimelinesQuery = (options: Options<GetTimelinesData>) => useQuery(getTimelinesOptions(options));

/**
 * Delete Workflow
 */
export const deleteWorkflowMutation = (options?: Partial<Options<DeleteWorkflowData>>): UseMutationOptions<unknown, DeleteWorkflowError, Options<DeleteWorkflowData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteWorkflowError, Options<DeleteWorkflowData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteWorkflow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkflowIdByNameQueryKey = (options: Options<GetWorkflowIdByNameData>) => createQueryKey('getWorkflowIdByName', options, false, ['workflow']);

/**
 * Get Workflow Id By Name
 */
export const getWorkflowIdByNameOptions = (options: Options<GetWorkflowIdByNameData>) => queryOptions<GetWorkflowIdByNameResponse, GetWorkflowIdByNameError, GetWorkflowIdByNameResponse, ReturnType<typeof getWorkflowIdByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflowIdByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowIdByNameQueryKey(options)
});

/**
 * Get Workflow Id By Name
 */
export const useGetWorkflowIdByNameQuery = (options: Options<GetWorkflowIdByNameData>) => useQuery(getWorkflowIdByNameOptions(options));

export const getJobQueryKey = (options: Options<GetJobData>) => createQueryKey('getJob', options, false, ['jobs']);

/**
 * Get Job
 */
export const getJobOptions = (options: Options<GetJobData>) => queryOptions<GetJobResponse, GetJobError, GetJobResponse, ReturnType<typeof getJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobQueryKey(options)
});

/**
 * Get Job
 */
export const useGetJobQuery = (options: Options<GetJobData>) => useQuery(getJobOptions(options));

export const getLogsQueryKey = (options: Options<GetLogsData>) => createQueryKey('getLogs', options, false, ['jobs']);

/**
 * Get Logs
 */
export const getLogsOptions = (options: Options<GetLogsData>) => queryOptions<GetLogsResponse, GetLogsError, GetLogsResponse, ReturnType<typeof getLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLogsQueryKey(options)
});

/**
 * Get Logs
 */
export const useGetLogsQuery = (options: Options<GetLogsData>) => useQuery(getLogsOptions(options));

export const getJobOutputsQueryKey = (options: Options<GetJobOutputsData>) => createQueryKey('getJobOutputs', options, false, ['outputs']);

/**
 * Get Job Outputs
 */
export const getJobOutputsOptions = (options: Options<GetJobOutputsData>) => queryOptions<GetJobOutputsResponse, GetJobOutputsError, GetJobOutputsResponse, ReturnType<typeof getJobOutputsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobOutputs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobOutputsQueryKey(options)
});

/**
 * Get Job Outputs
 */
export const useGetJobOutputsQuery = (options: Options<GetJobOutputsData>) => useQuery(getJobOutputsOptions(options));

export const getAllTagsQueryKey = (options?: Options<GetAllTagsData>) => createQueryKey('getAllTags', options, false, ['utils']);

/**
 * Get All Tags
 */
export const getAllTagsOptions = (options?: Options<GetAllTagsData>) => queryOptions<GetAllTagsResponse, DefaultError, GetAllTagsResponse, ReturnType<typeof getAllTagsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllTags({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllTagsQueryKey(options)
});

/**
 * Get All Tags
 */
export const useGetAllTagsQuery = (options?: Options<GetAllTagsData>) => useQuery(getAllTagsOptions(options));

export const streamEventsQueryKey = (options?: Options<StreamEventsData>) => createQueryKey('streamEvents', options, false, ['sse']);

/**
 * Stream Events
 */
export const streamEventsOptions = (options?: Options<StreamEventsData>) => queryOptions<unknown, StreamEventsError, unknown, ReturnType<typeof streamEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streamEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streamEventsQueryKey(options)
});

/**
 * Stream Events
 */
export const useStreamEventsQuery = (options?: Options<StreamEventsData>) => useQuery(streamEventsOptions(options));

export const getWorkflowLogsQueryKey = (options: Options<GetWorkflowLogsData>) => createQueryKey('getWorkflowLogs', options, false, ['logs']);

/**
 * Get Workflow Logs
 */
export const getWorkflowLogsOptions = (options: Options<GetWorkflowLogsData>) => queryOptions<GetWorkflowLogsResponse, GetWorkflowLogsError, GetWorkflowLogsResponse, ReturnType<typeof getWorkflowLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflowLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowLogsQueryKey(options)
});

/**
 * Get Workflow Logs
 */
export const useGetWorkflowLogsQuery = (options: Options<GetWorkflowLogsData>) => useQuery(getWorkflowLogsOptions(options));

export const streamWorkflowLogsSseQueryKey = (options: Options<StreamWorkflowLogsSseData>) => createQueryKey('streamWorkflowLogsSse', options, false, ['logs']);

/**
 * Stream Workflow Logs Sse
 *
 * 使用Server-Sent Events格式的实时日志流
 */
export const streamWorkflowLogsSseOptions = (options: Options<StreamWorkflowLogsSseData>) => queryOptions<unknown, StreamWorkflowLogsSseError, unknown, ReturnType<typeof streamWorkflowLogsSseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streamWorkflowLogsSse({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streamWorkflowLogsSseQueryKey(options)
});

/**
 * Stream Workflow Logs Sse
 *
 * 使用Server-Sent Events格式的实时日志流
 */
export const useStreamWorkflowLogsSseQuery = (options: Options<StreamWorkflowLogsSseData>) => useQuery(streamWorkflowLogsSseOptions(options));

export const listFilesQueryKey = (options: Options<ListFilesData>) => createQueryKey('listFiles', options, false, ['files']);

/**
 * List Files
 */
export const listFilesOptions = (options: Options<ListFilesData>) => queryOptions<ListFilesResponse, ListFilesError, ListFilesResponse, ReturnType<typeof listFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listFilesQueryKey(options)
});

/**
 * List Files
 */
export const useListFilesQuery = (options: Options<ListFilesData>) => useQuery(listFilesOptions(options));
