// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { cleanupConnections, debugConnections, deleteWorkflow, forceReconnect, getActivity, getAllTags, getAllUsers, getConfigfiles, getDetail, getJob, getJobOutputs, getJobs, getLogs, getOutputs, getProgress, getRuleDuration, getRuleError, getRuleGraph, getRuleStatus, getSnakefile, getSseStats, getStatus, getSystemResources, getTimelines, getUserSummary, getWorkflowIdByName, getWorkflowLogs, getWorkflows, type Options, postPruning, sendTestNotification, sseHealthCheck, streamEvents, streamWorkflowLogsSse } from '../sdk.gen';
import type { CleanupConnectionsData, DebugConnectionsData, DeleteWorkflowData, DeleteWorkflowError, ForceReconnectData, GetActivityData, GetActivityError, GetActivityResponse, GetAllTagsData, GetAllTagsResponse, GetAllUsersData, GetAllUsersResponse, GetConfigfilesData, GetConfigfilesError, GetConfigfilesResponse, GetDetailData, GetDetailError, GetDetailResponse, GetJobData, GetJobError, GetJobOutputsData, GetJobOutputsError, GetJobOutputsResponse, GetJobResponse, GetJobsData, GetJobsError, GetJobsResponse, GetLogsData, GetLogsError, GetOutputsData, GetOutputsError, GetOutputsResponse, GetProgressData, GetProgressError, GetProgressResponse, GetRuleDurationData, GetRuleDurationError, GetRuleDurationResponse, GetRuleErrorData, GetRuleErrorError, GetRuleErrorResponse, GetRuleGraphData, GetRuleGraphError, GetRuleGraphResponse, GetRuleStatusData, GetRuleStatusError, GetRuleStatusResponse, GetSnakefileData, GetSnakefileError, GetSseStatsData, GetStatusData, GetStatusError, GetStatusResponse, GetSystemResourcesData, GetTimelinesData, GetTimelinesError, GetTimelinesResponse, GetUserSummaryData, GetUserSummaryResponse, GetWorkflowIdByNameData, GetWorkflowIdByNameError, GetWorkflowIdByNameResponse, GetWorkflowLogsData, GetWorkflowLogsError, GetWorkflowsData, GetWorkflowsError, GetWorkflowsResponse, PostPruningData, PostPruningResponse, SendTestNotificationData, SseHealthCheckData, StreamEventsData, StreamEventsError, StreamWorkflowLogsSseData, StreamWorkflowLogsSseError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getSystemResourcesQueryKey = (options?: Options<GetSystemResourcesData>) => createQueryKey('getSystemResources', options);

/**
 * Get System Resources
 */
export const getSystemResourcesOptions = (options?: Options<GetSystemResourcesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSystemResourcesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemResources({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemResourcesQueryKey(options)
});

export const getUserSummaryQueryKey = (options?: Options<GetUserSummaryData>) => createQueryKey('getUserSummary', options);

/**
 * Get User Summary
 */
export const getUserSummaryOptions = (options?: Options<GetUserSummaryData>) => queryOptions<GetUserSummaryResponse, DefaultError, GetUserSummaryResponse, ReturnType<typeof getUserSummaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserSummary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserSummaryQueryKey(options)
});

export const getStatusQueryKey = (options: Options<GetStatusData>) => createQueryKey('getStatus', options);

/**
 * Get Status
 */
export const getStatusOptions = (options: Options<GetStatusData>) => queryOptions<GetStatusResponse, GetStatusError, GetStatusResponse, ReturnType<typeof getStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStatusQueryKey(options)
});

export const getActivityQueryKey = (options: Options<GetActivityData>) => createQueryKey('getActivity', options);

/**
 * Get Activity
 */
export const getActivityOptions = (options: Options<GetActivityData>) => queryOptions<GetActivityResponse, GetActivityError, GetActivityResponse, ReturnType<typeof getActivityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getActivity({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getActivityQueryKey(options)
});

export const getRuleErrorQueryKey = (options?: Options<GetRuleErrorData>) => createQueryKey('getRuleError', options);

/**
 * Get Rule Error
 */
export const getRuleErrorOptions = (options?: Options<GetRuleErrorData>) => queryOptions<GetRuleErrorResponse, GetRuleErrorError, GetRuleErrorResponse, ReturnType<typeof getRuleErrorQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleError({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleErrorQueryKey(options)
});

export const getRuleDurationQueryKey = (options?: Options<GetRuleDurationData>) => createQueryKey('getRuleDuration', options);

/**
 * Get Rule Duration
 */
export const getRuleDurationOptions = (options?: Options<GetRuleDurationData>) => queryOptions<GetRuleDurationResponse, GetRuleDurationError, GetRuleDurationResponse, ReturnType<typeof getRuleDurationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleDuration({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleDurationQueryKey(options)
});

/**
 * Post Pruning
 */
export const postPruningMutation = (options?: Partial<Options<PostPruningData>>): UseMutationOptions<PostPruningResponse, DefaultError, Options<PostPruningData>> => {
    const mutationOptions: UseMutationOptions<PostPruningResponse, DefaultError, Options<PostPruningData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPruning({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllUsersQueryKey = (options?: Options<GetAllUsersData>) => createQueryKey('getAllUsers', options);

/**
 * Get All Users
 */
export const getAllUsersOptions = (options?: Options<GetAllUsersData>) => queryOptions<GetAllUsersResponse, DefaultError, GetAllUsersResponse, ReturnType<typeof getAllUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllUsersQueryKey(options)
});

export const getJobsQueryKey = (options: Options<GetJobsData>) => createQueryKey('getJobs', options);

/**
 * Get Jobs
 */
export const getJobsOptions = (options: Options<GetJobsData>) => queryOptions<GetJobsResponse, GetJobsError, GetJobsResponse, ReturnType<typeof getJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getJobsInfiniteQueryKey = (options: Options<GetJobsData>): QueryKey<Options<GetJobsData>> => createQueryKey('getJobs', options, true);

/**
 * Get Jobs
 */
export const getJobsInfiniteOptions = (options: Options<GetJobsData>) => infiniteQueryOptions<GetJobsResponse, GetJobsError, InfiniteData<GetJobsResponse>, QueryKey<Options<GetJobsData>>, number | null | Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getJobs({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsInfiniteQueryKey(options)
});

export const getWorkflowsQueryKey = (options?: Options<GetWorkflowsData>) => createQueryKey('getWorkflows', options);

/**
 * Get Workflows
 */
export const getWorkflowsOptions = (options?: Options<GetWorkflowsData>) => queryOptions<GetWorkflowsResponse, GetWorkflowsError, GetWorkflowsResponse, ReturnType<typeof getWorkflowsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflows({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowsQueryKey(options)
});

export const getWorkflowsInfiniteQueryKey = (options?: Options<GetWorkflowsData>): QueryKey<Options<GetWorkflowsData>> => createQueryKey('getWorkflows', options, true);

/**
 * Get Workflows
 */
export const getWorkflowsInfiniteOptions = (options?: Options<GetWorkflowsData>) => infiniteQueryOptions<GetWorkflowsResponse, GetWorkflowsError, InfiniteData<GetWorkflowsResponse>, QueryKey<Options<GetWorkflowsData>>, number | null | Pick<QueryKey<Options<GetWorkflowsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetWorkflowsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkflows({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowsInfiniteQueryKey(options)
});

export const getRuleGraphQueryKey = (options: Options<GetRuleGraphData>) => createQueryKey('getRuleGraph', options);

/**
 * Get Rule Graph
 */
export const getRuleGraphOptions = (options: Options<GetRuleGraphData>) => queryOptions<GetRuleGraphResponse, GetRuleGraphError, GetRuleGraphResponse, ReturnType<typeof getRuleGraphQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleGraph({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleGraphQueryKey(options)
});

export const getDetailQueryKey = (options: Options<GetDetailData>) => createQueryKey('getDetail', options);

/**
 * Get Detail
 */
export const getDetailOptions = (options: Options<GetDetailData>) => queryOptions<GetDetailResponse, GetDetailError, GetDetailResponse, ReturnType<typeof getDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDetailQueryKey(options)
});

export const getRuleStatusQueryKey = (options: Options<GetRuleStatusData>) => createQueryKey('getRuleStatus', options);

/**
 * Get Rule Status
 */
export const getRuleStatusOptions = (options: Options<GetRuleStatusData>) => queryOptions<GetRuleStatusResponse, GetRuleStatusError, GetRuleStatusResponse, ReturnType<typeof getRuleStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRuleStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRuleStatusQueryKey(options)
});

export const getSnakefileQueryKey = (options: Options<GetSnakefileData>) => createQueryKey('getSnakefile', options);

/**
 * Get Snakefile
 */
export const getSnakefileOptions = (options: Options<GetSnakefileData>) => queryOptions<unknown, GetSnakefileError, unknown, ReturnType<typeof getSnakefileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSnakefile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSnakefileQueryKey(options)
});

export const getConfigfilesQueryKey = (options: Options<GetConfigfilesData>) => createQueryKey('getConfigfiles', options);

/**
 * Get Configfiles
 */
export const getConfigfilesOptions = (options: Options<GetConfigfilesData>) => queryOptions<GetConfigfilesResponse, GetConfigfilesError, GetConfigfilesResponse, ReturnType<typeof getConfigfilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConfigfiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConfigfilesQueryKey(options)
});

export const getProgressQueryKey = (options: Options<GetProgressData>) => createQueryKey('getProgress', options);

/**
 * Get Progress
 */
export const getProgressOptions = (options: Options<GetProgressData>) => queryOptions<GetProgressResponse, GetProgressError, GetProgressResponse, ReturnType<typeof getProgressQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProgress({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProgressQueryKey(options)
});

export const getTimelinesQueryKey = (options: Options<GetTimelinesData>) => createQueryKey('getTimelines', options);

/**
 * Get Timelines
 */
export const getTimelinesOptions = (options: Options<GetTimelinesData>) => queryOptions<GetTimelinesResponse, GetTimelinesError, GetTimelinesResponse, ReturnType<typeof getTimelinesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTimelines({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTimelinesQueryKey(options)
});

/**
 * Delete Workflow
 */
export const deleteWorkflowMutation = (options?: Partial<Options<DeleteWorkflowData>>): UseMutationOptions<unknown, DeleteWorkflowError, Options<DeleteWorkflowData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteWorkflowError, Options<DeleteWorkflowData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteWorkflow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkflowIdByNameQueryKey = (options: Options<GetWorkflowIdByNameData>) => createQueryKey('getWorkflowIdByName', options);

/**
 * Get Workflow Id By Name
 */
export const getWorkflowIdByNameOptions = (options: Options<GetWorkflowIdByNameData>) => queryOptions<GetWorkflowIdByNameResponse, GetWorkflowIdByNameError, GetWorkflowIdByNameResponse, ReturnType<typeof getWorkflowIdByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflowIdByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowIdByNameQueryKey(options)
});

export const getJobQueryKey = (options: Options<GetJobData>) => createQueryKey('getJob', options);

/**
 * Get Job
 */
export const getJobOptions = (options: Options<GetJobData>) => queryOptions<GetJobResponse, GetJobError, GetJobResponse, ReturnType<typeof getJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobQueryKey(options)
});

export const getLogsQueryKey = (options: Options<GetLogsData>) => createQueryKey('getLogs', options);

/**
 * Get Logs
 */
export const getLogsOptions = (options: Options<GetLogsData>) => queryOptions<unknown, GetLogsError, unknown, ReturnType<typeof getLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLogsQueryKey(options)
});

export const getOutputsQueryKey = (options: Options<GetOutputsData>) => createQueryKey('getOutputs', options);

/**
 * Get Outputs
 */
export const getOutputsOptions = (options: Options<GetOutputsData>) => queryOptions<GetOutputsResponse, GetOutputsError, GetOutputsResponse, ReturnType<typeof getOutputsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOutputs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOutputsQueryKey(options)
});

export const getJobOutputsQueryKey = (options: Options<GetJobOutputsData>) => createQueryKey('getJobOutputs', options);

/**
 * Get Job Outputs
 */
export const getJobOutputsOptions = (options: Options<GetJobOutputsData>) => queryOptions<GetJobOutputsResponse, GetJobOutputsError, GetJobOutputsResponse, ReturnType<typeof getJobOutputsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobOutputs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobOutputsQueryKey(options)
});

export const getAllTagsQueryKey = (options?: Options<GetAllTagsData>) => createQueryKey('getAllTags', options);

/**
 * Get All Tags
 */
export const getAllTagsOptions = (options?: Options<GetAllTagsData>) => queryOptions<GetAllTagsResponse, DefaultError, GetAllTagsResponse, ReturnType<typeof getAllTagsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllTags({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllTagsQueryKey(options)
});

export const streamEventsQueryKey = (options?: Options<StreamEventsData>) => createQueryKey('streamEvents', options);

/**
 * Stream Events
 *
 * Server-Sent Events endpoint for real-time database notifications.
 *
 * 客户端可以连接此端点接收实时通知:
 * - GET /api/v1/sse/events - 接收所有表变化
 * - GET /api/v1/sse/events?filters=workflows - 只接收workflows表变化
 * - GET /api/v1/sse/events?filters=jobs&workflow_id=123 - 接收workflows和jobs表变化
 */
export const streamEventsOptions = (options?: Options<StreamEventsData>) => queryOptions<unknown, StreamEventsError, unknown, ReturnType<typeof streamEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streamEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streamEventsQueryKey(options)
});

export const sseHealthCheckQueryKey = (options?: Options<SseHealthCheckData>) => createQueryKey('sseHealthCheck', options);

/**
 * Sse Health Check
 */
export const sseHealthCheckOptions = (options?: Options<SseHealthCheckData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof sseHealthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await sseHealthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: sseHealthCheckQueryKey(options)
});

export const getSseStatsQueryKey = (options?: Options<GetSseStatsData>) => createQueryKey('getSseStats', options);

/**
 * Get Sse Stats
 */
export const getSseStatsOptions = (options?: Options<GetSseStatsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSseStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSseStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSseStatsQueryKey(options)
});

/**
 * Send Test Notification
 */
export const sendTestNotificationMutation = (options?: Partial<Options<SendTestNotificationData>>): UseMutationOptions<unknown, DefaultError, Options<SendTestNotificationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SendTestNotificationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendTestNotification({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const debugConnectionsQueryKey = (options?: Options<DebugConnectionsData>) => createQueryKey('debugConnections', options);

/**
 * Debug Connections
 */
export const debugConnectionsOptions = (options?: Options<DebugConnectionsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof debugConnectionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await debugConnections({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: debugConnectionsQueryKey(options)
});

/**
 * Cleanup Connections
 */
export const cleanupConnectionsMutation = (options?: Partial<Options<CleanupConnectionsData>>): UseMutationOptions<unknown, DefaultError, Options<CleanupConnectionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CleanupConnectionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cleanupConnections({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Force Reconnect
 */
export const forceReconnectMutation = (options?: Partial<Options<ForceReconnectData>>): UseMutationOptions<unknown, DefaultError, Options<ForceReconnectData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ForceReconnectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await forceReconnect({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkflowLogsQueryKey = (options: Options<GetWorkflowLogsData>) => createQueryKey('getWorkflowLogs', options);

/**
 * Get Workflow Logs
 */
export const getWorkflowLogsOptions = (options: Options<GetWorkflowLogsData>) => queryOptions<unknown, GetWorkflowLogsError, unknown, ReturnType<typeof getWorkflowLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkflowLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkflowLogsQueryKey(options)
});

export const streamWorkflowLogsSseQueryKey = (options: Options<StreamWorkflowLogsSseData>) => createQueryKey('streamWorkflowLogsSse', options);

/**
 * Stream Workflow Logs Sse
 *
 * 使用Server-Sent Events格式的实时日志流
 */
export const streamWorkflowLogsSseOptions = (options: Options<StreamWorkflowLogsSseData>) => queryOptions<unknown, StreamWorkflowLogsSseError, unknown, ReturnType<typeof streamWorkflowLogsSseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streamWorkflowLogsSse({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streamWorkflowLogsSseQueryKey(options)
});
