// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CleanupConnectionsData, CleanupConnectionsResponses, DebugConnectionsData, DebugConnectionsResponses, DeleteWorkflowData, DeleteWorkflowErrors, DeleteWorkflowResponses, ForceReconnectData, ForceReconnectResponses, GetActivityData, GetActivityErrors, GetActivityResponses, GetAllTagsData, GetAllTagsResponses, GetAllUsersData, GetAllUsersResponses, GetConfigfilesData, GetConfigfilesErrors, GetConfigfilesResponses, GetDetailData, GetDetailErrors, GetDetailResponses, GetJobData, GetJobErrors, GetJobOutputsData, GetJobOutputsErrors, GetJobOutputsResponses, GetJobResponses, GetJobsData, GetJobsErrors, GetJobsResponses, GetLogsData, GetLogsErrors, GetLogsResponses, GetOutputsData, GetOutputsErrors, GetOutputsResponses, GetProgressData, GetProgressErrors, GetProgressResponses, GetRuleDurationData, GetRuleDurationErrors, GetRuleDurationResponses, GetRuleErrorData, GetRuleErrorErrors, GetRuleErrorResponses, GetRuleGraphData, GetRuleGraphErrors, GetRuleGraphResponses, GetRuleStatusData, GetRuleStatusErrors, GetRuleStatusResponses, GetSnakefileData, GetSnakefileErrors, GetSnakefileResponses, GetSseStatsData, GetSseStatsResponses, GetStatusData, GetStatusErrors, GetStatusResponses, GetSystemResourcesData, GetSystemResourcesResponses, GetTimelinesData, GetTimelinesErrors, GetTimelinesResponses, GetUserSummaryData, GetUserSummaryResponses, GetWorkflowIdByNameData, GetWorkflowIdByNameErrors, GetWorkflowIdByNameResponses, GetWorkflowLogsData, GetWorkflowLogsErrors, GetWorkflowLogsResponses, GetWorkflowsData, GetWorkflowsErrors, GetWorkflowsResponses, PostPruningData, PostPruningResponses, SendTestNotificationData, SendTestNotificationResponses, SseHealthCheckData, SseHealthCheckResponses, StreamEventsData, StreamEventsErrors, StreamEventsResponses, StreamWorkflowLogsSseData, StreamWorkflowLogsSseErrors, StreamWorkflowLogsSseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get System Resources
 */
export const getSystemResources = <ThrowOnError extends boolean = false>(options?: Options<GetSystemResourcesData, ThrowOnError>) => (options?.client ?? client).get<GetSystemResourcesResponses, unknown, ThrowOnError>({ url: '/api/v1/summary/resources', ...options });

/**
 * Get User Summary
 */
export const getUserSummary = <ThrowOnError extends boolean = false>(options?: Options<GetUserSummaryData, ThrowOnError>) => (options?.client ?? client).get<GetUserSummaryResponses, unknown, ThrowOnError>({ url: '/api/v1/summary/user', ...options });

/**
 * Get Status
 */
export const getStatus = <ThrowOnError extends boolean = false>(options: Options<GetStatusData, ThrowOnError>) => (options.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({ url: '/api/v1/summary/status', ...options });

/**
 * Get Activity
 */
export const getActivity = <ThrowOnError extends boolean = false>(options: Options<GetActivityData, ThrowOnError>) => (options.client ?? client).get<GetActivityResponses, GetActivityErrors, ThrowOnError>({ url: '/api/v1/summary/activity', ...options });

/**
 * Get Rule Error
 */
export const getRuleError = <ThrowOnError extends boolean = false>(options?: Options<GetRuleErrorData, ThrowOnError>) => (options?.client ?? client).get<GetRuleErrorResponses, GetRuleErrorErrors, ThrowOnError>({ url: '/api/v1/summary/rule_error', ...options });

/**
 * Get Rule Duration
 */
export const getRuleDuration = <ThrowOnError extends boolean = false>(options?: Options<GetRuleDurationData, ThrowOnError>) => (options?.client ?? client).get<GetRuleDurationResponses, GetRuleDurationErrors, ThrowOnError>({ url: '/api/v1/summary/rule_duration', ...options });

/**
 * Post Pruning
 */
export const postPruning = <ThrowOnError extends boolean = false>(options?: Options<PostPruningData, ThrowOnError>) => (options?.client ?? client).post<PostPruningResponses, unknown, ThrowOnError>({ url: '/api/v1/summary/pruning', ...options });

/**
 * Get All Users
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => (options?.client ?? client).get<GetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/v1/workflows/users', ...options });

/**
 * Get Jobs
 */
export const getJobs = <ThrowOnError extends boolean = false>(options: Options<GetJobsData, ThrowOnError>) => (options.client ?? client).get<GetJobsResponses, GetJobsErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/jobs', ...options });

/**
 * Get Workflows
 */
export const getWorkflows = <ThrowOnError extends boolean = false>(options?: Options<GetWorkflowsData, ThrowOnError>) => (options?.client ?? client).get<GetWorkflowsResponses, GetWorkflowsErrors, ThrowOnError>({ url: '/api/v1/workflows/', ...options });

/**
 * Get Rule Graph
 */
export const getRuleGraph = <ThrowOnError extends boolean = false>(options: Options<GetRuleGraphData, ThrowOnError>) => (options.client ?? client).get<GetRuleGraphResponses, GetRuleGraphErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/rule_graph', ...options });

/**
 * Get Detail
 */
export const getDetail = <ThrowOnError extends boolean = false>(options: Options<GetDetailData, ThrowOnError>) => (options.client ?? client).get<GetDetailResponses, GetDetailErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/detail', ...options });

/**
 * Get Rule Status
 */
export const getRuleStatus = <ThrowOnError extends boolean = false>(options: Options<GetRuleStatusData, ThrowOnError>) => (options.client ?? client).get<GetRuleStatusResponses, GetRuleStatusErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/rule_status', ...options });

/**
 * Get Snakefile
 */
export const getSnakefile = <ThrowOnError extends boolean = false>(options: Options<GetSnakefileData, ThrowOnError>) => (options.client ?? client).get<GetSnakefileResponses, GetSnakefileErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/snakefile', ...options });

/**
 * Get Configfiles
 */
export const getConfigfiles = <ThrowOnError extends boolean = false>(options: Options<GetConfigfilesData, ThrowOnError>) => (options.client ?? client).get<GetConfigfilesResponses, GetConfigfilesErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/configfiles', ...options });

/**
 * Get Progress
 */
export const getProgress = <ThrowOnError extends boolean = false>(options: Options<GetProgressData, ThrowOnError>) => (options.client ?? client).get<GetProgressResponses, GetProgressErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/progress', ...options });

/**
 * Get Timelines
 */
export const getTimelines = <ThrowOnError extends boolean = false>(options: Options<GetTimelinesData, ThrowOnError>) => (options.client ?? client).get<GetTimelinesResponses, GetTimelinesErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}/timelines', ...options });

/**
 * Delete Workflow
 */
export const deleteWorkflow = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkflowData, ThrowOnError>) => (options.client ?? client).delete<DeleteWorkflowResponses, DeleteWorkflowErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_id}', ...options });

/**
 * Get Workflow Id By Name
 */
export const getWorkflowIdByName = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowIdByNameData, ThrowOnError>) => (options.client ?? client).get<GetWorkflowIdByNameResponses, GetWorkflowIdByNameErrors, ThrowOnError>({ url: '/api/v1/workflows/by_name', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>) => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/api/v1/jobs/{job_id}/detail', ...options });

/**
 * Get Logs
 */
export const getLogs = <ThrowOnError extends boolean = false>(options: Options<GetLogsData, ThrowOnError>) => (options.client ?? client).get<GetLogsResponses, GetLogsErrors, ThrowOnError>({ url: '/api/v1/jobs/{job_id}/logs', ...options });

/**
 * Get Outputs
 */
export const getOutputs = <ThrowOnError extends boolean = false>(options: Options<GetOutputsData, ThrowOnError>) => (options.client ?? client).get<GetOutputsResponses, GetOutputsErrors, ThrowOnError>({ url: '/api/v1/outputs/{workflow_id}/outputs', ...options });

/**
 * Get Job Outputs
 */
export const getJobOutputs = <ThrowOnError extends boolean = false>(options: Options<GetJobOutputsData, ThrowOnError>) => (options.client ?? client).get<GetJobOutputsResponses, GetJobOutputsErrors, ThrowOnError>({ url: '/api/v1/outputs/{workflow_id}/rule_outputs', ...options });

/**
 * Get All Tags
 */
export const getAllTags = <ThrowOnError extends boolean = false>(options?: Options<GetAllTagsData, ThrowOnError>) => (options?.client ?? client).get<GetAllTagsResponses, unknown, ThrowOnError>({ url: '/api/v1/utils/tags', ...options });

/**
 * Stream Events
 *
 * Server-Sent Events endpoint for real-time database notifications.
 *
 * 客户端可以连接此端点接收实时通知:
 * - GET /api/v1/sse/events - 接收所有表变化
 * - GET /api/v1/sse/events?filters=workflows - 只接收workflows表变化
 * - GET /api/v1/sse/events?filters=jobs&workflow_id=123 - 接收workflows和jobs表变化
 */
export const streamEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) => (options?.client ?? client).get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({ url: '/api/v1/sse/events', ...options });

/**
 * Sse Health Check
 */
export const sseHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<SseHealthCheckData, ThrowOnError>) => (options?.client ?? client).get<SseHealthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/health', ...options });

/**
 * Get Sse Stats
 */
export const getSseStats = <ThrowOnError extends boolean = false>(options?: Options<GetSseStatsData, ThrowOnError>) => (options?.client ?? client).get<GetSseStatsResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/stats', ...options });

/**
 * Send Test Notification
 */
export const sendTestNotification = <ThrowOnError extends boolean = false>(options?: Options<SendTestNotificationData, ThrowOnError>) => (options?.client ?? client).post<SendTestNotificationResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/test-notification', ...options });

/**
 * Debug Connections
 */
export const debugConnections = <ThrowOnError extends boolean = false>(options?: Options<DebugConnectionsData, ThrowOnError>) => (options?.client ?? client).get<DebugConnectionsResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/debug/connections', ...options });

/**
 * Cleanup Connections
 */
export const cleanupConnections = <ThrowOnError extends boolean = false>(options?: Options<CleanupConnectionsData, ThrowOnError>) => (options?.client ?? client).post<CleanupConnectionsResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/cleanup-connections', ...options });

/**
 * Force Reconnect
 */
export const forceReconnect = <ThrowOnError extends boolean = false>(options?: Options<ForceReconnectData, ThrowOnError>) => (options?.client ?? client).post<ForceReconnectResponses, unknown, ThrowOnError>({ url: '/api/v1/sse/reconnect', ...options });

/**
 * Get Workflow Logs
 */
export const getWorkflowLogs = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowLogsData, ThrowOnError>) => (options.client ?? client).get<GetWorkflowLogsResponses, GetWorkflowLogsErrors, ThrowOnError>({ url: '/api/v1/logs/{workflow_id}', ...options });

/**
 * Stream Workflow Logs Sse
 *
 * 使用Server-Sent Events格式的实时日志流
 */
export const streamWorkflowLogsSse = <ThrowOnError extends boolean = false>(options: Options<StreamWorkflowLogsSseData, ThrowOnError>) => (options.client ?? client).get<StreamWorkflowLogsSseResponses, StreamWorkflowLogsSseErrors, ThrowOnError>({ url: '/api/v1/logs/{workflow_id}/sse', ...options });
