// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth_jwt_login_api_v1_auth_jwt_login_post
 */
export type BodyAuthJwtLoginApiV1AuthJwtLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * FileNode
 */
export type FileNode = {
    /**
     * Title
     */
    title: string;
    /**
     * Key
     */
    key: string;
    /**
     * Isleaf
     */
    isLeaf: boolean;
    /**
     * Filesize
     */
    fileSize?: number | null;
    /**
     * Icon
     */
    icon: string;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobDetailResponse
 */
export type JobDetailResponse = {
    /**
     * Rule Name
     */
    rule_name: string;
    status: Status;
    /**
     * Workflow Id
     */
    workflow_id?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Shellcmd
     */
    shellcmd?: string | null;
    /**
     * Wildcards
     */
    wildcards?: {
        [key: string]: unknown;
    } | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Resources
     */
    resources?: {
        [key: string]: unknown;
    } | null;
    /**
     * Directory
     */
    directory?: string | null;
    /**
     * Input
     */
    input?: Array<string> | null;
    /**
     * Output
     */
    output?: Array<string> | null;
    /**
     * Log
     */
    log?: Array<string> | null;
};

/**
 * JobListResponse
 *
 * Schema for job list response
 */
export type JobListResponse = {
    /**
     * Jobs
     */
    jobs: Array<JobResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * JobResponse
 *
 * Schema for job response
 */
export type JobResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Rule Id
     */
    rule_id?: number | null;
    /**
     * Rule Name
     */
    rule_name?: string | null;
    /**
     * Workflow Id
     */
    workflow_id?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Threads
     */
    threads?: number | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Shellcmd
     */
    shellcmd?: string | null;
    /**
     * Wildcards
     */
    wildcards?: {
        [key: string]: unknown;
    } | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Resources
     */
    resources?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PathContent
 */
export type PathContent = {
    /**
     * Content
     */
    content: string;
    /**
     * Path
     */
    path: string;
};

/**
 * ReportPayload
 */
export type ReportPayload = {
    /**
     * Event
     */
    event: string;
    /**
     * Record
     */
    record: {
        [key: string]: unknown;
    };
    /**
     * Context
     */
    context: {
        [key: string]: unknown;
    };
};

/**
 * ResourcesSummary
 */
export type ResourcesSummary = {
    /**
     * Cpu Idle Cores
     */
    cpu_idle_cores: number;
    /**
     * Cpu Total Cores
     */
    cpu_total_cores: number | null;
    /**
     * Mem Total Gb
     */
    mem_total_GB: number;
    /**
     * Mem Available Gb
     */
    mem_available_GB: number;
};

/**
 * RuleStatusResponse
 */
export type RuleStatusResponse = {
    /**
     * Success
     */
    success: string;
    /**
     * Running
     */
    running: string;
    /**
     * Error
     */
    error: string;
    /**
     * Total
     */
    total: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ServiceStatus
 */
export type ServiceStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Status
 */
export type Status = 'ERROR' | 'RUNNING' | 'SUCCESS' | 'WAITING' | 'UNKNOWN';

/**
 * StatusSummary
 */
export type StatusSummary = {
    /**
     * Total
     */
    total: number;
    /**
     * Success
     */
    success: number;
    /**
     * Running
     */
    running: number;
    /**
     * Error
     */
    error: number;
};

/**
 * SystemHealthResponse
 */
export type SystemHealthResponse = {
    database: ServiceStatus;
    sse: ServiceStatus;
    /**
     * Overall Status
     */
    overall_status: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * UserTokenCreate
 */
export type UserTokenCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Ttl Days
     */
    ttl_days?: number | null;
};

/**
 * UserTokenList
 */
export type UserTokenList = {
    /**
     * Tokens
     */
    tokens: Array<UserTokenResponse>;
};

/**
 * UserTokenResponse
 */
export type UserTokenResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Token
     */
    token: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkflowDetialResponse
 */
export type WorkflowDetialResponse = {
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * User
     */
    user?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * End Time
     */
    end_time: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress?: number | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Snakefile
     */
    snakefile: string | null;
    /**
     * Directory
     */
    directory?: string | null;
    /**
     * Configfiles
     */
    configfiles?: Array<string> | null;
    /**
     * Flowo Directory
     */
    flowo_directory?: string | null;
};

/**
 * WorkflowListResponse
 *
 * Schema for workflow list response
 */
export type WorkflowListResponse = {
    /**
     * Workflows
     */
    workflows: Array<WorkflowResponse>;
    /**
     * Total
     */
    total: number | null;
    /**
     * Limit
     */
    limit: number | null;
    /**
     * Offset
     */
    offset: number | null;
};

/**
 * WorkflowResponse
 *
 * Schema for workflow response
 */
export type WorkflowResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Directory
     */
    directory?: string | null;
    /**
     * Snakefile
     */
    snakefile: boolean;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * User
     */
    user?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Configfiles
     */
    configfiles: boolean;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Progress
     */
    progress?: number | null;
    /**
     * Total Jobs
     */
    total_jobs: number;
};

export type AuthJwtLoginData = {
    body: BodyAuthJwtLoginApiV1AuthJwtLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/jwt/login';
};

export type AuthJwtLoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthJwtLoginResponse = AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/jwt/logout';
};

export type AuthJwtLogoutErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthJwtLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterRegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterError = RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterResponse = RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type UsersCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type UsersCurrentUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserResponse = UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type UsersPatchCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserError = UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserResponse = UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{id}';
};

export type UsersUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{id}';
};

export type UsersPatchUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserError = UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserResponse = UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type GetSystemResourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/summary/resources';
};

export type GetSystemResourcesResponses = {
    /**
     * Successful Response
     */
    200: ResourcesSummary;
};

export type GetSystemResourcesResponse = GetSystemResourcesResponses[keyof GetSystemResourcesResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Item
         */
        item: 'job' | 'workflow';
    };
    url: '/api/v1/summary/status';
};

export type GetStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors];

export type GetStatusResponses = {
    /**
     * Successful Response
     */
    200: StatusSummary;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetActivityData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Item
         */
        item: 'rule' | 'user' | 'tag';
        /**
         * Start At
         */
        start_at?: string | null;
        /**
         * End At
         */
        end_at?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/summary/activity';
};

export type GetActivityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivityError = GetActivityErrors[keyof GetActivityErrors];

export type GetActivityResponses = {
    /**
     * Response Get Activity Api V1 Summary Activity Get
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetActivityResponse = GetActivityResponses[keyof GetActivityResponses];

export type GetRuleErrorData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start At
         */
        start_at?: string | null;
        /**
         * End At
         */
        end_at?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/summary/rule_error';
};

export type GetRuleErrorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleErrorError = GetRuleErrorErrors[keyof GetRuleErrorErrors];

export type GetRuleErrorResponses = {
    /**
     * Response Get Rule Error Api V1 Summary Rule Error Get
     *
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type GetRuleErrorResponse = GetRuleErrorResponses[keyof GetRuleErrorResponses];

export type GetRuleDurationData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start At
         */
        start_at?: string | null;
        /**
         * End At
         */
        end_at?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/summary/rule_duration';
};

export type GetRuleDurationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleDurationError = GetRuleDurationErrors[keyof GetRuleDurationErrors];

export type GetRuleDurationResponses = {
    /**
     * Response Get Rule Duration Api V1 Summary Rule Duration Get
     *
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: number;
        };
    };
};

export type GetRuleDurationResponse = GetRuleDurationResponses[keyof GetRuleDurationResponses];

export type PostPruningData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/summary/pruning';
};

export type PostPruningResponses = {
    /**
     * Response Post Pruning Api V1 Summary Pruning Post
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type PostPruningResponse = PostPruningResponses[keyof PostPruningResponses];

export type GetSystemHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/summary/health';
};

export type GetSystemHealthResponses = {
    /**
     * Successful Response
     */
    200: SystemHealthResponse;
};

export type GetSystemHealthResponse = GetSystemHealthResponses[keyof GetSystemHealthResponses];

export type GetWorkflowsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Maximum number of workflows to return
         */
        limit?: number | null;
        /**
         * Offset
         *
         * Number of workflows to skip
         */
        offset?: number | null;
        /**
         * Order By Started
         *
         * Order by start time (True) or ID (False)
         */
        order_by_started?: boolean;
        /**
         * Descending
         *
         * Order in descending order (newest first)
         */
        descending?: boolean;
        /**
         * User
         *
         * Filter by user string (legacy)
         */
        user?: string | null;
        /**
         * Status
         *
         * Filter by workflow status (RUNNING, SUCCESS, ERROR, UNKNOWN)
         */
        status?: Status | null;
        /**
         * Tags
         *
         * Filter by tags (comma-separated)
         */
        tags?: string | null;
        /**
         * Name
         *
         * Filter by workflow name
         */
        name?: string | null;
        /**
         * Start At
         *
         * Filter workflows started after this time
         */
        start_at?: string | null;
        /**
         * End At
         *
         * Filter workflows ended before this time
         */
        end_at?: string | null;
    };
    url: '/api/v1/workflows/';
};

export type GetWorkflowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowsError = GetWorkflowsErrors[keyof GetWorkflowsErrors];

export type GetWorkflowsResponses = {
    /**
     * Successful Response
     */
    200: WorkflowListResponse;
};

export type GetWorkflowsResponse = GetWorkflowsResponses[keyof GetWorkflowsResponses];

export type GetJobsData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Maximum number of jobs to return
         */
        limit?: number | null;
        /**
         * Offset
         *
         * Number of jobs to skip
         */
        offset?: number | null;
        /**
         * Order By Started
         *
         * Order by start time (True) or ID (False)
         */
        order_by_started?: boolean;
        /**
         * Descending
         *
         * Order in descending order (newest first)
         */
        descending?: boolean;
        /**
         * Rule Name
         *
         * Filter jobs by rule_name
         */
        rule_name?: string | null;
        /**
         * Status
         *
         * Filter jobs by status
         */
        status?: Status | null;
    };
    url: '/api/v1/workflows/{workflow_id}/jobs';
};

export type GetJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors];

export type GetJobsResponses = {
    /**
     * Successful Response
     */
    200: JobListResponse;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type GetRuleGraphData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/rule_graph';
};

export type GetRuleGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleGraphError = GetRuleGraphErrors[keyof GetRuleGraphErrors];

export type GetRuleGraphResponses = {
    /**
     * Response Get Rule Graph Api V1 Workflows  Workflow Id  Rule Graph Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRuleGraphResponse = GetRuleGraphResponses[keyof GetRuleGraphResponses];

export type GetDetailData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/detail';
};

export type GetDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDetailError = GetDetailErrors[keyof GetDetailErrors];

export type GetDetailResponses = {
    /**
     * Successful Response
     */
    200: WorkflowDetialResponse;
};

export type GetDetailResponse = GetDetailResponses[keyof GetDetailResponses];

export type GetRuleStatusData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/rule_status';
};

export type GetRuleStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleStatusError = GetRuleStatusErrors[keyof GetRuleStatusErrors];

export type GetRuleStatusResponses = {
    /**
     * Response Get Rule Status Api V1 Workflows  Workflow Id  Rule Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: RuleStatusResponse;
    };
};

export type GetRuleStatusResponse = GetRuleStatusResponses[keyof GetRuleStatusResponses];

export type GetSnakefileData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/snakefile';
};

export type GetSnakefileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSnakefileError = GetSnakefileErrors[keyof GetSnakefileErrors];

export type GetSnakefileResponses = {
    /**
     * Successful Response
     */
    200: PathContent;
};

export type GetSnakefileResponse = GetSnakefileResponses[keyof GetSnakefileResponses];

export type GetWorkflowLogData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/log';
};

export type GetWorkflowLogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowLogError = GetWorkflowLogErrors[keyof GetWorkflowLogErrors];

export type GetWorkflowLogResponses = {
    /**
     * Successful Response
     */
    200: PathContent;
};

export type GetWorkflowLogResponse = GetWorkflowLogResponses[keyof GetWorkflowLogResponses];

export type GetConfigfilesData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/configfiles';
};

export type GetConfigfilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConfigfilesError = GetConfigfilesErrors[keyof GetConfigfilesErrors];

export type GetConfigfilesResponses = {
    /**
     * Response Get Configfiles Api V1 Workflows  Workflow Id  Configfiles Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetConfigfilesResponse = GetConfigfilesResponses[keyof GetConfigfilesResponses];

export type GetProgressData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: {
        /**
         * Return Total Jobs Number
         */
        return_total_jobs_number?: boolean;
    };
    url: '/api/v1/workflows/{workflow_id}/progress';
};

export type GetProgressErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProgressError = GetProgressErrors[keyof GetProgressErrors];

export type GetProgressResponses = {
    /**
     * Response Get Progress Api V1 Workflows  Workflow Id  Progress Get
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetProgressResponse = GetProgressResponses[keyof GetProgressResponses];

export type GetTimelinesData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/timelines';
};

export type GetTimelinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimelinesError = GetTimelinesErrors[keyof GetTimelinesErrors];

export type GetTimelinesResponses = {
    /**
     * Response Get Timelines Api V1 Workflows  Workflow Id  Timelines Get
     *
     * Successful Response
     */
    200: {
        [key: string]: Array<unknown>;
    };
};

export type GetTimelinesResponse = GetTimelinesResponses[keyof GetTimelinesResponses];

export type DeleteWorkflowData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type DeleteWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowError = DeleteWorkflowErrors[keyof DeleteWorkflowErrors];

export type DeleteWorkflowResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkflowIdByNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         *
         * Workflow name to search for
         */
        name: string;
    };
    url: '/api/v1/workflows/by_name';
};

export type GetWorkflowIdByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowIdByNameError = GetWorkflowIdByNameErrors[keyof GetWorkflowIdByNameErrors];

export type GetWorkflowIdByNameResponses = {
    /**
     * Response Get Workflow Id By Name Api V1 Workflows By Name Get
     *
     * Successful Response
     */
    200: string;
};

export type GetWorkflowIdByNameResponse = GetWorkflowIdByNameResponses[keyof GetWorkflowIdByNameResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/detail';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobDetailResponse;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type GetLogsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}/logs';
};

export type GetLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLogsError = GetLogsErrors[keyof GetLogsErrors];

export type GetLogsResponses = {
    /**
     * Response Get Logs Api V1 Jobs  Job Id  Logs Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type GetJobOutputsData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query: {
        /**
         * Rule Name
         */
        rule_name: string;
    };
    url: '/api/v1/outputs/{workflow_id}/rule_outputs';
};

export type GetJobOutputsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobOutputsError = GetJobOutputsErrors[keyof GetJobOutputsErrors];

export type GetJobOutputsResponses = {
    /**
     * Response Get Job Outputs Api V1 Outputs  Workflow Id  Rule Outputs Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetJobOutputsResponse = GetJobOutputsResponses[keyof GetJobOutputsResponses];

export type GetAllTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/tags';
};

export type GetAllTagsResponses = {
    /**
     * Response Get All Tags Api V1 Utils Tags Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetAllTagsResponse = GetAllTagsResponses[keyof GetAllTagsResponses];

export type GetClientConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/client-config';
};

export type GetClientConfigResponses = {
    /**
     * Response Get Client Config Api V1 Utils Client Config Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string | number;
    };
};

export type GetClientConfigResponse = GetClientConfigResponses[keyof GetClientConfigResponses];

export type GetSseTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sse/ticket';
};

export type GetSseTicketResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamEventsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/sse/events';
};

export type StreamEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamEventsError = StreamEventsErrors[keyof StreamEventsErrors];

export type StreamEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Workflow Id
         */
        workflow_id: string;
        /**
         * Path
         *
         * Parent directory path (relative)
         */
        path?: string;
    };
    url: '/api/v1/files/list';
};

export type ListFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
    /**
     * Response List Files Api V1 Files List Get
     *
     * Successful Response
     */
    200: Array<FileNode>;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type ReadFileData = {
    body?: never;
    path: {
        /**
         * File Path
         */
        file_path: string;
    };
    query?: never;
    url: '/api/v1/files/files/{file_path}';
};

export type ReadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileError = ReadFileErrors[keyof ReadFileErrors];

export type ReadFileResponses = {
    /**
     * Successful Response
     */
    200: PathContent;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type ReportEventData = {
    body: ReportPayload;
    path?: never;
    query?: never;
    url: '/api/v1/reports/';
};

export type ReportEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportEventError = ReportEventErrors[keyof ReportEventErrors];

export type ReportEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CloseWorkflowData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    url: '/api/v1/reports/close';
};

export type CloseWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloseWorkflowError = CloseWorkflowErrors[keyof CloseWorkflowErrors];

export type CloseWorkflowResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tokens/';
};

export type ListTokensResponses = {
    /**
     * Successful Response
     */
    200: UserTokenList;
};

export type ListTokensResponse = ListTokensResponses[keyof ListTokensResponses];

export type CreateTokenData = {
    body: UserTokenCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tokens/';
};

export type CreateTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
    /**
     * Successful Response
     */
    200: UserTokenResponse;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type DeleteTokenData = {
    body?: never;
    path: {
        /**
         * Token Id
         */
        token_id: string;
    };
    query?: never;
    url: '/api/v1/tokens/{token_id}';
};

export type DeleteTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTokenError = DeleteTokenErrors[keyof DeleteTokenErrors];

export type DeleteTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
