name: Conditional Docker Build and Push

on:
  push:
    branches:
      - release
    paths:
      - "backend/app/**"
      - "frontend/src/**"
      - ".gitea/workflows/**" # 当工作流文件本身变更时也触发

env:
  REGISTRY: 172.16.3.223:5000
  BACKEND_IMAGE: iremeta/flowo
  FRONTEND_IMAGE: iremeta/flowo-frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend-changed: ${{ steps.changes.outputs.backend }}
      frontend-changed: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: https://gitea.miaonas.fun:14443/actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以便比较

      - name: Detect changes
        id: changes
        run: |
          # 检查 backend/app 目录是否有变更
          if git diff --name-only HEAD~1 HEAD | grep -q '^backend/app/'; then
            echo "backend=true" >> $GITHUB_OUTPUT
            echo "Backend changes detected"
          else
            echo "backend=false" >> $GITHUB_OUTPUT
            echo "No backend changes detected"
          fi

          # 检查 frontend/src 目录是否有变更
          if git diff --name-only HEAD~1 HEAD | grep -q '^frontend/src/'; then
            echo "frontend=true" >> $GITHUB_OUTPUT
            echo "Frontend changes detected"
          else
            echo "frontend=false" >> $GITHUB_OUTPUT
            echo "No frontend changes detected"
          fi

  build-backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    steps:
      - uses: https://gitea.miaonas.fun:14443/actions/checkout@v4
      - uses: https://gitea.miaonas.fun:14443/actions/setup-buildx-action@v3
        with:
          driver-opts: image=172.16.3.223:5000/moby/buildkit:buildx-stable-1
          buildkitd-config-inline: |
            [registry."172.16.3.223:5000"]
              http = true

      - name: Build and push backend
        uses: https://gitea.miaonas.fun:14443/actions/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=172.16.3.223:5000/build/flowo:buildcache
          cache-to: type=registry,ref=172.16.3.223:5000/build/flowo:buildcache,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    steps:
      - uses: https://gitea.miaonas.fun:14443/actions/checkout@v4
      - uses: https://gitea.miaonas.fun:14443/actions/setup-buildx-action@v3
        with:
          driver-opts: image=172.16.3.223:5000/moby/buildkit:buildx-stable-1
          buildkitd-config-inline: |
            [registry."172.16.3.223:5000"]
              http = true

      - name: Build and push frontend
        uses: https://gitea.miaonas.fun:14443/actions/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=172.16.3.223:5000/build/flowo-frontend:buildcache
          cache-to: type=registry,ref=172.16.3.223:5000/build/flowo-frontend:buildcache,mode=max
          build-args: |
            VITE_API_BASE_PATH=http://flowo.irep.com
