apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowo-frontend
  namespace: flowo
  labels:
    app: flowo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flowo-frontend
  template:
    metadata:
      labels:
        app: flowo-frontend
    spec:
      containers:
      - name: flowo-frontend
        image: 172.16.3.223:5000/iremeta/flowo-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: flowo-config
              key: TZ
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: flowo-frontend
  namespace: flowo
  labels:
    app: flowo-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: flowo-frontend
  type: ClusterIP
