apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowo-ingress
  namespace: flowo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Optional: for SSL certificates
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect for local
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: flowo.dashboard.com  # Fixed typo: dashborad -> dashboard
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: caddy
            port:
              number: 80
  tls:  # Optional: for SSL certificates
  - hosts:
    - flowo.dashboard.com
    secretName: flowo-tls
