"""add catalog_files and catalog_file_versions tables

Revision ID: 067b69763188
Revises: 87413392d668
Create Date: 2026-05-07 11:46:55.896417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067b69763188'
down_revision: Union[str, None] = '87413392d668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_slug', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_sha256', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_slug', 'path')
    )
    op.create_index(op.f('ix_catalog_files_catalog_slug'), 'catalog_files', ['catalog_slug'], unique=False)
    op.create_table('catalog_file_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_sha256', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['catalog_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version')
    )
    op.create_index(op.f('ix_catalog_file_versions_file_id'), 'catalog_file_versions', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_file_versions_file_id'), table_name='catalog_file_versions')
    op.drop_table('catalog_file_versions')
    op.drop_index(op.f('ix_catalog_files_catalog_slug'), table_name='catalog_files')
    op.drop_table('catalog_files')
    # ### end Alembic commands ###
