"""Remove catalog file and batch import tables

Revision ID: 3602ee30de87
Revises: e3f4a5b6c7d8
Create Date: 2026-05-08 20:29:00.782202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3602ee30de87'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_file_versions_file_id'), table_name='catalog_file_versions')
    op.drop_table('catalog_file_versions')
    op.drop_index(op.f('ix_catalog_files_catalog_slug'), table_name='catalog_files')
    op.drop_table('catalog_files')
    op.drop_index(op.f('ix_batch_imports_catalog_created'), table_name='batch_imports')
    op.drop_index(op.f('ix_batch_imports_catalog_slug'), table_name='batch_imports')
    # Use cascade=True or drop in correct order
    op.drop_table('batch_imports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('catalog_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_sha256', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lines', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_modified_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_imports.id'], name=op.f('catalog_files_batch_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('catalog_files_pkey')),
    sa.UniqueConstraint('catalog_slug', 'path', name=op.f('catalog_files_catalog_slug_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_catalog_files_catalog_slug'), 'catalog_files', ['catalog_slug'], unique=False)
    op.create_table('batch_imports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('catalog_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('commit_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('batch_imports_pkey'))
    )
    op.create_index(op.f('ix_batch_imports_catalog_slug'), 'batch_imports', ['catalog_slug'], unique=False)
    op.create_index(op.f('ix_batch_imports_catalog_created'), 'batch_imports', ['catalog_slug', 'created_at'], unique=False)
    op.create_table('catalog_file_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_sha256', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['catalog_files.id'], name=op.f('catalog_file_versions_file_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('catalog_file_versions_pkey')),
    sa.UniqueConstraint('file_id', 'version', name=op.f('catalog_file_versions_file_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_catalog_file_versions_file_id'), 'catalog_file_versions', ['file_id'], unique=False)
    # ### end Alembic commands ###
