"""add_smtp_to_system_settings

Revision ID: 46f7ce4fa652
Revises: 906f79ea5749
Create Date: 2026-04-10 10:24:39.106429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f7ce4fa652'
down_revision: Union[str, None] = '906f79ea5749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_user', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_password', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_from', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_use_tls', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'smtp_use_tls')
    op.drop_column('system_settings', 'smtp_from')
    op.drop_column('system_settings', 'smtp_password')
    op.drop_column('system_settings', 'smtp_user')
    op.drop_column('system_settings', 'smtp_port')
    op.drop_column('system_settings', 'smtp_host')
    # ### end Alembic commands ###
