"""Add catalogs table

Revision ID: 4fd23b2d16da
Revises: c1a2b3d4e5f6
Create Date: 2026-03-01 22:39:05.358563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4fd23b2d16da'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rulegraph_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_slug'), 'catalogs', ['slug'], unique=True)
    op.drop_constraint(op.f('user_settings_user_id_key'), 'user_settings', type_='unique')
    op.add_column('workflows', sa.Column('catalog_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'catalogs', ['catalog_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'catalog_id')
    op.create_unique_constraint(op.f('user_settings_user_id_key'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_catalogs_slug'), table_name='catalogs')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
