"""add code and language to rules

Revision ID: 8b3ac7e7b37c
Revises: ba4e3285cd2d
Create Date: 2026-02-13 10:38:04.579552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3ac7e7b37c'
down_revision: Union[str, None] = 'ba4e3285cd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('code', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'language')
    op.drop_column('rules', 'code')
    # ### end Alembic commands ###
