"""add batch_imports table and batch_id to catalog_files

Revision ID: ab4bc3ac69db
Revises: 067b69763188
Create Date: 2026-05-07 14:28:50.765963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4bc3ac69db'
down_revision: Union[str, None] = '067b69763188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_slug', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_imports_catalog_created', 'batch_imports', ['catalog_slug', 'created_at'], unique=False)
    op.create_index(op.f('ix_batch_imports_catalog_slug'), 'batch_imports', ['catalog_slug'], unique=False)
    op.add_column('catalog_files', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'catalog_files', 'batch_imports', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_files', type_='foreignkey')
    op.drop_column('catalog_files', 'batch_id')
    op.drop_index(op.f('ix_batch_imports_catalog_slug'), table_name='batch_imports')
    op.drop_index('ix_batch_imports_catalog_created', table_name='batch_imports')
    op.drop_table('batch_imports')
    # ### end Alembic commands ###
