name: Deploy Mock to GitHub Pages

on:
  push:
    branches:
      - mock
    paths:
      - "frontend/src/**"
      - "frontend/public/**"
      - ".github/workflows/deploy-mock.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Initialize MSW
        working-directory: ./frontend
        run: |
          # Initialize MSW in public directory first
          npx msw init public --save
          # Copy to src for development
          cp public/mockServiceWorker.js src/

      - name: Build for GitHub Pages
        working-directory: ./frontend
        env:
          VITE_API_BASE_PATH: ""
          VITE_DISABLE_SSE: "true"
          VITE_ENABLE_MSW: "true"
          NODE_ENV: production
        run: |
          # Build the static files
          pnpm run build

          # Ensure MSW worker is in the dist directory
          if [ ! -f "dist/mockServiceWorker.js" ]; then
            echo "Copying MSW service worker to dist..."
            cp public/mockServiceWorker.js dist/
          fi

          # Verify the file exists
          ls -la dist/mockServiceWorker.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
